In [5]:
import numpy as np
import math
import torch

x = -3.19
y = 3
theta = 0
state = torch.tensor([x,y,theta], dtype=torch.float32)
epi_len = 10

ep_t = 0
time_int = 0.01

ref_trajectory=[[-1.5+5.8*math.cos(0.24*time_int*t+1.5), 5.8*math.sin(0.24*t*time_int+1.5)] for t in range(epi_len)]
state_d = torch.tensor(ref_trajectory)

l = torch.tensor([0.7,0.7])
ini_width = 0.2
rho_f = torch.tensor([0.2,0.2])
rho_0 = (torch.abs(torch.tensor([x, y]) - state_d[0, :]) + ini_width).clone().detach()

gamma_np = [(rho_0 - rho_f)* torch.exp(-l*time_int*t) + rho_f for t in range(epi_len)]





In [ ]:
state_d


In [ ]:
for _ in range(epi_len):
    
    

In [6]:
gamma_np


[tensor([0.2000, 0.2000]),
 tensor([0.1853, 0.1805]),
 tensor([0.1706, 0.1610]),
 tensor([0.1559, 0.1415]),
 tensor([0.1412, 0.1220]),
 tensor([0.1265, 0.1025]),
 tensor([0.1118, 0.0830]),
 tensor([0.0971, 0.0635]),
 tensor([0.0824, 0.0440]),
 tensor([0.0677, 0.0245])]

In [2]:
x = -3.19
y = 3
theta = 0
state = np.array([x,y,theta])

#RL constants
ep_t = 0

time_int = 0.01
# t2 = timestep*time_int
#reference trajectory
ref_trajectory=[[-1.5+5.8*math.cos(0.24*time_int*t+1.5), 5.8*math.sin(0.24*t*time_int+1.5)] for t in range(epi_len)]
state_d = np.array(ref_trajectory)

#Funnel for soft constraint currently values are according to paper
l = np.array([0.7,0.7])
ini_width = 0.2 #higher the value more is the initial funnel width
rho_f = np.array([0.2,0.2])
rho_0 = np.array(abs(np.array([x,y])- state_d[0,:]) + ini_width )
gamma = np.array([(rho_0 - rho_f)*np.exp(-l*time_int*t) + rho_f for t in range(epi_len)])


In [4]:
gamma

array([[2.30027577, 2.98547092],
       [2.28562518, 2.96604071],
       [2.27107678, 2.94674604],
       [2.25662986, 2.92758595],
       [2.24228373, 2.90855952],
       [2.22803766, 2.88966581],
       [2.21389097, 2.87090389],
       [2.19984296, 2.85227285],
       [2.18589294, 2.83377177],
       [2.17204023, 2.81539974]])

In [3]:
gamma_tensor = torch.tensor(gamma)
gamma_tensor

tensor([[2.3003, 2.9855],
        [2.2856, 2.9660],
        [2.2711, 2.9467],
        [2.2566, 2.9276],
        [2.2423, 2.9086],
        [2.2280, 2.8897],
        [2.2139, 2.8709],
        [2.1998, 2.8523],
        [2.1859, 2.8338],
        [2.1720, 2.8154]], dtype=torch.float64)

In [ ]:
are_equal = np.array_equal(gamma, gamma_np)

if are_equal:
    print("yes")
else:
    print("no")

In [ ]:
gamma_np

In [ ]:
gamma

In [ ]:
lb_soft = state_d - gamma
ub_soft = state_d + gamma
phi_ini_L = tf.constant([0.0, 0.0], dtype=tf.float32, name='phi_ini_L')
phi_ini_U = tf.constant([0.0, 0.0], dtype=tf.float32, name='phi_ini_U')

In [ ]:
print(l.shape)
print(rho_f.shape)
print(rho_0.shape)
print(gamma.shape)

In [ ]:
print(l)
print("###")
print(rho_f)
print("###")
print(rho_0)
print("###")
print(gamma)

In [ ]:
import tensorflow as tf
l = tf.constant([0.7, 0.7], dtype=tf.float32, name='l')
rho_f = tf.constant([0.2, 0.2], dtype=tf.float32, name='rho_f')
rho_0 = tf.abs(state[:2] - state_d[0, :]) + ini_width
gamma = (rho_0 - rho_f) * tf.exp(-l * time_int * tf.range(epi_len, dtype=tf.float32))

In [ ]:
print(l.shape)
print(rho_f.shape)
print(rho_0.shape)
print(gamma.shape)

In [ ]:
print(l)
print("####")
print(rho_f)
print("###")
print(rho_0)
print("###")
print(gamma)

In [ ]:

self.action_space = Box(low = np.array([-1,-1,-1]), #lower bounds for vel_x,vel_y,omega
                                     high=np.array([1,1,1])) #upper bounds for vel_x,vel_y,omega

self.observation_space = Box(low = np.array([-6.58,-4.63,-math.pi]), #lower bounds of state
                                      high=np.array([6.58,4.63,math.pi]),dtype=np.float64) #upper bounds of state
self.epi_len = 100


        #states
        self.x = -3.19
        self.y = 3
        self.theta = 0
        self.state = torch.tensor([self.x, self.y, self.theta], dtype=torch.float64)

        # RL constants
        self.ep_t = 0
        self.time_int = 0.01

        # Reference trajectory
        ref_trajectory = [[-1.5 + 5.8 * math.cos(0.24 * self.time_int * t + 1.5),
                           5.8 * math.sin(0.24 * t * self.time_int + 1.5)] for t in range(self.epi_len)]
        self.state_d = torch.tensor(ref_trajectory, dtype=torch.float64)

        # Funnel for soft constraint currently values are according to paper
        l = torch.tensor([0.7, 0.7])
        ini_width = 0.2  # higher the value more is the initial funnel width
        rho_f = torch.tensor([0.2, 0.2])
        rho_0 = torch.abs(torch.tensor([self.x, self.y]) - self.state_d[0, :]) + ini_width
        self.x