In [11]:
import numpy as np
import math
x = -3.19
y = 3
theta = 0
state = np.array([x,y,theta])
epi_len = 10

ep_t = 0
time_int = 0.01

ref_trajectory=[[-1.5+5.8*math.cos(0.24*time_int*t+1.5), 5.8*math.sin(0.24*t*time_int+1.5)] for t in range(epi_len)]
state_d = np.array(ref_trajectory)

l = np.array([0.7,0.7])
ini_width = 0.2
rho_f = np.array([0.2,0.2])
rho_0 = np.array(abs(np.array([x,y])- state_d[0,:]) + ini_width)
gamma_np = np.array([(rho_0 - rho_f)*np.exp(-l*time_int*t) + rho_f for t in range(epi_len)])
gamma = tf.convert_to_tensor(gamma_np, dtype=tf.float32, name='gamma')


In [12]:
lb_soft = state_d - gamma
ub_soft = state_d + gamma
phi_ini_L = tf.constant([0.0, 0.0], dtype=tf.float32, name='phi_ini_L')
phi_ini_U = tf.constant([0.0, 0.0], dtype=tf.float32, name='phi_ini_U')

In [9]:
print(l.shape)
print(rho_f.shape)
print(rho_0.shape)
print(gamma.shape)

(2,)
(2,)
(2,)
(10, 2)


In [10]:
print(l)
print("###")
print(rho_f)
print("###")
print(rho_0)
print("###")
print(gamma)

[0.7 0.7]
###
[0.2 0.2]
###
[2.30027577 2.98547092]
###
tf.Tensor(
[[2.3002758 2.985471 ]
 [2.2856252 2.9660406]
 [2.2710767 2.946746 ]
 [2.25663   2.9275858]
 [2.2422838 2.9085596]
 [2.2280376 2.8896658]
 [2.213891  2.870904 ]
 [2.199843  2.8522727]
 [2.1858928 2.8337717]
 [2.1720402 2.8153996]], shape=(10, 2), dtype=float32)


In [6]:
import tensorflow as tf
l = tf.constant([0.7, 0.7], dtype=tf.float32, name='l')
rho_f = tf.constant([0.2, 0.2], dtype=tf.float32, name='rho_f')
rho_0 = tf.abs(state[:2] - state_d[0, :]) + ini_width
gamma = (rho_0 - rho_f) * tf.exp(-l * time_int * tf.range(epi_len, dtype=tf.float32))

InvalidArgumentError: cannot compute Sub as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:Sub] name: 

In [6]:
print(l.shape)
print(rho_f.shape)
print(rho_0.shape)
print(gamma.shape)

(2,)
(2,)
(2,)


In [7]:
print(l)
print("####")
print(rho_f)
print("###")
print(rho_0)
print("###")
print(gamma)

tf.Tensor([0.7 0.7], shape=(2,), dtype=float32)
####
tf.Tensor([0.2 0.2], shape=(2,), dtype=float32)
###
tf.Tensor([2.30027577 2.98547092], shape=(2,), dtype=float64)
